url: https://craftguystradingco.com
baseurl: 

# Site settings
title: The Craft Guys Trading Company
email: hello@craftguystradingco.com
description: "We Know Craft"


# Team names, titles and social links
people:
- name: Steiner Roberts
  pic: steiner
  position: Co-Founder
  bio: We call him Steineey. Craft Guys was born out his passion for finding the best craft beer and sharing it with as many people as possible. Ask him about it next time you see him sat at the bar as he loves talking about it! His favorite style of beer is a clear West Coast IPA or a crisp Pilsner.

- name: Mike Shemeld
  pic: mike
  position: Co-Founder
  bio: Mikey got hooked on craft beer whilst travelling to the US on business. Now, his obsession is to share what he finds with as many beer lovers and aficionados as possible. His favorite style is a West Coast IPA, Black IPA and a solid Porter.

- name: Jason Cooper
  pic: jason
  position: Co-Founder
  bio: Cooper is where the North America Development happens. From Ohio, Cooper is an advocate of good craft beer and likes most styles, but his firm favorite is a New England IPA and all things hazy. Well, we all can’t be perfect I guess.

- name: Laura Eft
  pic: laura
  position: North America Buying Representative
  bio: Laura is a momma and a beer lover with a passion for discovering the best beers out there. U.S. craft beer and spirits are more than just our favorite drinks, they are the product of an authentic and passionate community. Her years of management and restaurant experience lead her here and she is incredibly proud to be part of this community. Her palate is rather eclectic, but loves New England IPAs and sour beers.
  social:
    - title: instagram
      url: http://instagram.com/brewmomma

- name: Brittani Robinson
  pic: brittani
  position: North America Buying Representative
  bio: Brittani has a passion and love for all things craft beer and cocktails. She has a wealth of sales and management experience within the industry and her favorite style of beer is a good New England IPA.

- name: Sandie Roberts
  pic: sandie
  position: Branding and Marketing
  bio: Sandie has a wealth of experience and knowledge in branding & marketing, having worked with many household names. Being a coeliac, her options are limited with beer and gets over excited when we find a new gluten free beer!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/weknowcraft
  - title: twitter
    url: http://twitter.com/weknowcraft
  - title: facebook
    url: http://facebook.com/weknowcraft


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Main Street
  - line: Marysville, OH 43040

# Build settings
markdown: kramdown
permalink: pretty